Rent/Controllers/ProposalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rent.DomainModels.Models;
using Rent.ServiceLayers;
using Rent.ViewModels.ProposalViewModels;

namespace Rent.Controllers
{
    public class ProposalsController : Controller
    {
        private readonly IProposalsService proposalsService;
        private readonly UserManager<User> userManager;
        private readonly IProductsService productsService;

        public ProposalsController(IProposalsService proposalsService, UserManager<User> userManager,
            IProductsService productsService)
        {
            this.proposalsService = proposalsService;
            this.userManager = userManager;
            this.productsService = productsService;
        }

        // GET: IncomingProposals
        public async Task<IActionResult> IncomingProposals(string? userName)
        {
            var user = await userManager.FindByNameAsync(userName);
            //if (user!=null)
            //{
            //    var proposals = proposalsService.GetProposalsByUserId(user.Id).Where(u => u.OwnerId == user.Id)
            //        .OrderByDescending(p => p.ProposalAdded).OrderByDescending(p => p.ProposalClosed).OrderBy(p => p.ProposalStatusId);
            //    return View(proposals);
            //}
            if (user != null)
            {
                ViewBag.UserId = user.Id;
                return View();
            }
            return RedirectToAction("Home", "Index");
        }

        // GET: OutgoingProposals
        public async Task<IActionResult> OutgoingProposals(string? userName)
        {
            var user = await userManager.FindByNameAsync(userName);
            if (user != null)
            {
                //var proposals = proposalsService.GetProposalsByUserId(user.Id).Where(u => u.BuyerId == user.Id)
                //    .OrderByDescending(p => p.ProposalAdded).OrderByDescending(p => p.ProposalClosed).OrderBy(p => p.ProposalStatusId);
                //return View(proposals);
                ViewBag.UserId = user.Id;
                return View();

            }
            return RedirectToAction("Home", "Index");
        }

        [HttpGet]
        public PartialViewResult _FilteredInboxProposals(string userId, string selection)
        {
            var proposals = proposalsService.GetProposalsByUserId(userId).Where(u=>u.OwnerId==userId);
                if (selection!="All")
                {
                    proposals = proposals.Where(p => p.ProposalStatus.StatusName == selection);
                }
            return PartialView(proposals.OrderByDescending(p => p.ProposalAdded));
        }


        [HttpGet]
        public PartialViewResult _FilteredOutboxProposals(string userId, string selection)
        {
            var proposals = proposalsService.GetProposalsByUserId(userId).Where(u => u.BuyerId == userId);

            if (selection != "All")
            {
                proposals = proposals.Where(p => p.ProposalStatus.StatusName == selection);
            }
            return PartialView(proposals.OrderByDescending(p => p.ProposalAdded));
        }
        // GET: Proposals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proposal = await proposalsService.GetProposalByProposalId((int)id);
            if (proposal == null)
            {
                return NotFound();
            }

            EditProposalDetailsViewModel proposalToEdit = new EditProposalDetailsViewModel()
            {
                ProposedPrice = proposal.ProposedPrice,
                ProposedRentEndDate = proposal.ProposedRentEndDate,
                ProposedRentStartDate = proposal.ProposedRentStartDate,
                ProposalMessage = proposal.ProposalMessage,
                ProposalType=proposal.ProposalType,
                ProposalTypeId=proposal.ProposalTypeId,
                Product =proposal.Product,
                ProductId = proposal.ProductId,
                ProposedAmount=proposal.ProposedAmount
                
            };
            return View(proposalToEdit);
        }

        // POST: Proposals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditProposalDetailsViewModel proposalToEdit)
        {
            if (id != proposalToEdit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await proposalsService.UpdateProposalDetails(proposalToEdit);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProposalExists(proposalToEdit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("OutgoingProposals", new { userName = User.Identity.Name});
            }
            return View(proposalToEdit);
        }

        // GET: Proposals/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            await proposalsService.DeleteProposal(id);
            return RedirectToAction("OutgoingProposals", new { userName = User.Identity.Name });
        }
        public async Task<IActionResult> AcceptOrRejectProposal(int proposalId, int statusId, int productId)
        {
            var responseDate = new DateTime();
            responseDate = DateTime.Now;
            var proposal = await proposalsService.GetProposalByProposalId(proposalId);
            //if the proposal is accepted the product.availableAmount should also be decreased
            if (statusId==2)
            {
               var product = await productsService.GetProductToUpdate(productId);
                proposal.Product.CurrentlyRented = proposal.Product.CurrentlyRented + proposal.ProposedAmount;
                await productsService.UpdateProductDetails(product);

            }

            await proposalsService.AcceptOrRejectProposal(proposalId, statusId, responseDate);
            return RedirectToAction("IncomingProposals", new { userName = User.Identity.Name });
        }

        private bool ProposalExists(int id)
        {
            return proposalsService.GetProposals().Any(p => p.Id == id);
        }
    }
}

Rent/ViewComponents/MessagesViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rent.DomainModels.Models;
using Rent.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rent.ViewComponents
{
    public class MessagesViewComponent : ViewComponent
    {
        private readonly IMessageRepository mr;
        private readonly UserManager<User> um;

        public MessagesViewComponent(IMessageRepository mr, UserManager<User> um)
        {
            this.mr = mr;
            this.um = um;
        }

        public async Task<IViewComponentResult> InvokeAsync(string userName)
        {
            var user = await um.FindByNameAsync(userName);

            //var messageList = mr.GetMessagesForUser(user.Id).Result.Where(m => m.Recipient.UserName == user.UserName && m.IsRead == false);
            var unreadMessagesCount = mr.GetUnreadInboxMessagesCount(user.Id).Result;
            return View(unreadMessagesCount);
        }
    }
}

Rent/ViewComponents/SearchBarViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Rent.DomainModels.Models;
using Rent.ServiceLayers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rent.ViewComponents
{
    public class SearchBarViewComponent:ViewComponent
    {
        private readonly ICategoriesService cs;

        public SearchBarViewComponent(ICategoriesService cs)
        {
            this.cs = cs;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            IEnumerable<Category> list;
            list = await cs.GetCategories();
            return View(list);
        }
    }
}

Rent/ViewComponents/WishlistViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Rent.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rent.ViewComponents
{
    public class WishlistViewComponent:ViewComponent
    {
        private readonly IWishListProdsRepository wr;

        public WishlistViewComponent(IWishListProdsRepository wr)
        {
            this.wr = wr;
        }

        public async Task<IViewComponentResult> InvokeAsync(string userName)
        {
            var wishList = await wr.GetWishListProducts(userName);
            return View(wishList);
        }
    }
}

Rent/Views/Shared/_CategoriesPartial.cshtml
@model IEnumerable<Category>
@*<div class="list-group mt-4">
        <a asp-controller="Home" asp-action="Index" class="list-group-item">All</a>
        @foreach (var item in Model)
        {
            <a asp-controller="Home" asp-action="Index" asp-route-Id="@item.Id" class="list-group-item">@item.CategoryName</a>
        }
    </div>*@


<div class="list-group mt-4">
    @*<div class="just-padding">

                <a href="#item-1" class="list-group-item" data-toggle="collapse">
                    <i class="fas fa-angle-right mr-2"></i>Item 1
                </a>
                <div class="list-group collapse" id="item-1">

                </div>
        </div>*@


    <a asp-controller="Home" asp-action="Index" asp-route-id="All" class="list-group-item">All</a>
    @{
        var i = 1;
        foreach (var category in Model)
        {
            <a href="#item-@i" class="list-group-item partial-category-block" data-toggle="collapse">
                @category.CategoryName<i class="fas fa-angle-right mr-2"></i>
            </a>
            <div class="list-group collapse" id="item-@i">
                @foreach (var subcategory in category.Subcategories)
                {
                    <a asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="@subcategory.Id" class="subcategory-link">
                        @subcategory.SubcategoryName
                    </a>
                }
            </div>
            ++i;
        }
    }

    @*Maybe price filtration also should be included*@
    @*<div class="mt-3 filter-price-block">
        <div>
            <input type="text" class="form-control filter-price-input" aria-label="Amount (to the nearest dollar)">

        </div>
        <div>
            <input type="text" class="form-control filter-price-input" aria-label="Amount (to the nearest dollar)">
        </div>
    </div>*@
</div>

@*<script>
        console.log('test');
    </script>*@
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

<script>
    $('.list-group-item').on('click', function () {
        $('.fas', this)
            .toggleClass('fa-angle-right')
            .toggleClass('fa-angle-down');
    });
</script>

Rent/Views/Shared/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@{ 
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = x.Name }).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "/" : $"{Context.Request.Path}{Context.Request.QueryString}";
}

<div class="form-group">
    <form asp-action="CultureManagement" asp-controller="Home" method="post" asp-route-returnUrl="@returnUrl">
        <select class="form-control" name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList"
                onchange="this.form.submit()"></select>
    </form>
</div>

Rent/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="~/css/bootstrap.min.css" />


    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="~/css/slick.css" />
    <link type="text/css" rel="stylesheet" href="~/css/slick-theme.css" />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="~/css/nouislider.min.css" />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet" />


    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/css/style.css" />
</head>


<body>
    <header>
        <div id="top-header">
            <div class="container">
                <ul class="header-links pull-left">
                    <li><a href="#"><i class="fa fa-phone"></i> +994-55-425-27-72</a></li>
                    <li><a href="#"><i class="fa fa-location-arrow"></i> Duisburg Strasse 15</a></li>
                </ul>
                <ul class="header-links pull-right">
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <!-- Example split danger button -->
                            @if (User.Identity.Name == "admin@rent.com")
                            {
                                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="btn btn-info">@localizer["AdminPanelLink"]</a>
                            }
                            <div class="user-control-block">
                                <label style="font-size:15px;color:white;">@User.Identity.Name</label>
                                <div>
                                    <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="AccountInfo">
                                            @localizer["UserAccountLink"]
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        <a asp-area="" asp-controller="Account" asp-action="Logout" class="dropdown-item">
                                            @localizer["UserLogoutLink"]
                                        </a>
                                    </div>
                                </div>
                            </div>
                            @*<div class="btn-group">
                                    <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="AccountInfo">
                                            @localizer["UserAccountLink"]
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        <a asp-area="" asp-controller="Account" asp-action="Logout" class="dropdown-item">
                                            @localizer["UserLogoutLink"]
                                        </a>
                                    </div>
                                </div>*@
                        }
                        else
                        {
                            <a asp-area="" asp-controller="Account" asp-action="Register" class="float-right btn btn-primary">@localizer["SignUpLinkText"]</a>
                            <a asp-area="" asp-controller="Account" asp-action="Login" class="float-right btn btn-success">@localizer["LoginLinkText"]</a>

                        }
                    </li>
                </ul>
            </div>
        </div>
        <div id="header">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <!-- LOGO -->
                    <div class="col-md-3">
                        <div class="header-logo">
                            <a href="#" class="logo">
                                <img src="~/Images/buy-sell-rent-property.png" style="width:250px;height:75px;" alt="">
                            </a>
                        </div>
                    </div>
                    <!-- /LOGO -->
                    <!-- SEARCH BAR -->
                    <div class="col-md-6">
                        <div class="header-search">
                            @await Component.InvokeAsync("SearchBar")
                            @*<form>
                                    <select class="input-select">
                                        <option value="0">All Categories</option>
                                        <option value="1">Category 01</option>
                                        <option value="1">Category 02</option>
                                    </select>
                                    <input class="input" placeholder="Search here">
                                    <button class="search-btn">Search</button>
                                </form>*@
                        </div>
                    </div>
                    <!-- /SEARCH BAR -->
                    <!-- ACCOUNT -->
                    <div class="col-md-3 clearfix">
                        <div class="header-ctn">
                            <!-- Wishlist -->
                            @if (User.Identity.IsAuthenticated == true)
                            {
                                @await Component.InvokeAsync("Wishlist", new { userName = User.Identity.Name });

                                @await Component.InvokeAsync("Messages", new { userName = User.Identity.Name });
                            }
                            <!-- /Wishlist -->
                            <!-- Menu Toogle -->
                            <div class="menu-toggle">
                                <a href="#">
                                    <i class="fa fa-bars"></i>
                                    <span>Menu</span>
                                </a>
                            </div>
                            <!-- /Menu Toogle -->
                        </div>
                    </div>
                    <!-- /ACCOUNT -->
                </div>
                <!-- row -->
            </div>
            <!-- container -->
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rent</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@localizer["HomeLink"]</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Details">Details</a>
                            </li>*@
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Products">Products</a>
                            </li>*@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Proposals" asp-action="IncomingProposals" asp-route-userName="@User.Identity.Name">
                                    @localizer["ProposalsLink"]
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index" asp-route-userName="@User.Identity.Name">
                                    @localizer["ProductsLink"]
                                </a>
                            </li>
                        }
                    </ul>
                </div>
                <partial name="_Culture" />

                @*<form class="form-inline">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">*@
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GoranBoy
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @if (User.Identity.IsAuthenticated == true)
    {
        <script src="~/js/site.js"></script>
    }
    @RenderSection("Scripts", required: false)
    @*<script src="~/js/signalr/dist/browser/signalr.js"></script>
        <script src="~/js/wishlistCount.js"></script>*@
</body>
</html>